/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.rmuhamedgaliev.woodpecker;

import lombok.extern.java.Log;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.telegram.telegrambots.ApiContextInitializer;

import javax.annotation.PostConstruct;

@Log
@SpringBootApplication
public class App implements CommandLineRunner {

    @PostConstruct
    public void init(){
        ApiContextInitializer.init();
    }

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) throws Exception {

    }
}
