app:
  telegram:
    token: 1050558739:AAEBT5CyU7wb-SBrT4WJ9-76QHy3ul8T7u4
    name: citronium_assistant_bot
  youtrack:
    token: perm:YWRtaW4=.NDMtMA==.2r9IttPSUnAs1f5bolRWX8jZTA8qO4
    host: http://localhost:8080
    infra-project: 0-0
spring:
  main:
    web-application-type: none
  datasource:
    name: sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file:wa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
