app:
  telegram:
    token: 1050558739:AAEBT5CyU7wb-SBrT4WJ9-76QHy3ul8T7u4
    name: citronium_assistant_bot
  youtrack:
    token: perm:cmluYXQubXVoYW1lZGdhbGlldg==.NjAtMTM=.tZxXZ4ZsDizNzoLvl0tRmz2BJJ63V7
    host: https://youtrack.citronium.com
    infra-project: 69-83
spring:
  main:
    web-application-type: none
  datasource:
    name: sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file:wa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
