/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.woodpeckeryt.youtracksdk;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {

    }
}
